name: tests
on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  run-checks:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14', '1.18']

    name: run-checks-with-go-v${{ matrix.go }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Go Version
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checks
        run: |
          VERBOSE=1 ./run-checks

  coverage:
    name: "codecov"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Run
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          name: "Delta Report"
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
